### ISSUE TITLE
Let's get lighthouse points with Now 2

### ISSUE THREAD

**Issue by TejasQ** [pingboard/next-pwa-boilerplate#1]
Now 2 is a powerhouse that, using serverless, really allows developers to optimize each route individually, fine tuning for performance. Let's highlight this by upgrading this project to Now 2? I love the project by the way! Thanks for making it! 💞

**Comment by timothyis** [comment]
Agreed! Next.js also supports a `target: "serverless"` config which allows Next.js pages to be built into individual lambda outputs. See an example here: https://github.com/zeit/now-examples/blob/master/nextjs/next.config.js#L2 (currently requires next@canary release) 
Much faster!

**Comment by seejamescode** [comment]
Took me a half-hour of learning, but [this example](https://github.com/hanford/next-offline/tree/master/examples/now2) helped me figure it out! The page-based lambda outputs sound like a great thing to upgrade to once it is on the GA release of Next.

Please let me know if there is something I could be doing better with Now!
